from os import environ

# AWS_ACCESS_KEY_ID = environ['AWS_ACCESS_KEY_ID']
# AWS_SECRET_ACCESS_KEY = environ['AWS_SECRET_ACCESS_KEY']
#
# CHANNEL_ACCESS_TOKEN = environ['CHANNEL_ACCESS_TOKEN']
# CHANNEL_SECRET = environ['CHANNEL_SECRET']

AWS_ACCESS_KEY_ID = 'AKIAR4NDUH53GWDLQFNM'
AWS_SECRET_ACCESS_KEY = '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'

CHANNEL_ACCESS_TOKEN = '+WxmXMuaJ7JstdctvSL4EK6sQsvELBeGBcgdRqLVQwfoLuifSII97rFi6Uf7Y2AdkODV7ZH6gKCGFxOYpz594Fiq31BDY' \
                       'ZCmtPgQJLD/l56Q0bsxwVS4P20CUI55r17cGYMeegGVylGxlnICp4ojFgdB04t89/1O/w1cDnyilFU='
CHANNEL_SECRET = '2fa83d60d7034793f32d60e8dbe48746'